### ISSUE TITLE
Why ??

### ISSUE THREAD

**Issue by lamhoangtung** [Animeakihabara/US-Medical-Insurance-Costs-#1]
Why this repo have both `main` and `master` branch ???

Why do the `main` branch is empty ??? If it is suppose to be deleted, why it still there and become the default branch ??

Why ???

**Comment by DLH06** [comment]
This old guy needs more time to feel convenient with new git features. Don't rush.
`master` flashback Q(. _ .)Q

**Comment by lamhoangtung** [comment]
LOL, I still use `master` only
